# Development notice
# Run it with the following:
# deckor alias init -f example/docker-compose.node.yml
version: '3.4'
services:
  app:
    image: node:16-alpine
    volumes:
      - ${PWD}:/app
    working_dir: /app
    labels:
      - "deckor.alias.node=docker compose -f example/docker-compose.node.yml run --rm -u $(id -u):$(id -g) app node"
      - "deckor.alias.npm=docker compose -f example/docker-compose.node.yml run --rm -u $(id -u):$(id -g) app npm"
      - "deckor.alias.npx=docker compose -f example/docker-compose.node.yml run --rm -u $(id -u):$(id -g) app npx"
      - "deckor.alias.yarn=docker compose -f example/docker-compose.node.yml run --rm -u $(id -u):$(id -g) app yarn"
